openapi: 3.0.0
info:
  title: Time Deposit Management API
  version: 1.0.0
  description: API for managing time deposits, calculating interest, and retrieving time deposits with their withdrawals.
servers:
  - url: http://localhost:8080/
    description: Local development server
tags:
  - name: Time Deposits
    description: Operations related to Time Deposits
paths:
  "/time-deposits":
    get:
      summary: Get all Time Deposits
      operationId: getAllTimeDeposits
      tags:
        - Time Deposits
      responses:
        '200':
          description: A list of all time deposits with their withdrawals.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListResponseTimeDeposits'
  "/time-deposits/update-balances":
    post:
      summary: Trigger Update of All Time Deposit Balances
      operationId: updateAllTimeDepositBalances
      tags:
        - Time Deposits
      requestBody: # Explicitly state no request body
        content: {}
        required: false
      responses:
        '202':
          description: Request accepted for processing. Balance update will be performed asynchronously.
components:
  schemas:
    ListResponse:
      type: object
      properties:
        data:
          type: array
          items: {}
      description: Generic response wrapper for lists.
    ListResponseTimeDeposits:
      allOf:
        - "$ref": "#/components/schemas/ListResponse"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/TimeDepositResponse"
    TimeDepositResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Unique identifier of the time deposit.
          example: 1
        planType:
          $ref: '#/components/schemas/TimeDepositPlanType'
        balance:
          type: string
          format: decimal
          description: Current balance of the time deposit, formatted to 2 decimal places.
          example: "1000.00"
        days:
          type: integer
          format: int32
          description: Number of days the time deposit has been active.
          example: 30
        withdrawals:
          type: array
          items:
            $ref: '#/components/schemas/WithdrawalResponse'
          description: List of withdrawals associated with this time deposit.
    TimeDepositPlanType:
      type: string
      enum:
        - BASIC
        - STUDENT
        - PREMIUM
      description: Type of the time deposit plan.
    WithdrawalResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Unique identifier of the withdrawal.
          example: 101
        amount:
          type: string
          format: decimal
          description: Amount of the withdrawal, formatted to 2 decimal places.
          example: "50.00"
        date:
          type: string
          format: date
          description: Date of the withdrawal.
          example: "2025-07-01"