CREATE SCHEMA IF NOT EXISTS time_deposits;

CREATE TABLE IF NOT EXISTS time_deposits.time_deposits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_type VARCHAR(255) NOT NULL,
    days INTEGER NOT NULL,
    balance DECIMAL(19, 2) NOT NULL
);

CREATE  TABLE  IF NOT EXISTS time_deposits.withdrawals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_deposit_id INTEGER NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    date TIMESTAMP NOT NULL,
    FOREIGN KEY (time_deposit_id) REFERENCES time_deposits.time_deposits(id)
);